package demo.vo;

import com.ctvit.framework.core.domain.BaseBean;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

public class Room extends BaseBean implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.ROOM_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private Long roomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.ROOM_NAME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private String roomName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.BUILDING_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private Long buildingId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.ROOM_NO
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private String roomNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.PRICE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.CREATE_TIME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.OPEN_DATE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private Date openDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.IMAGE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private byte[] image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RMS2.ROOM
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.ROOM_ID
	 * @return  the value of RMS2.ROOM.ROOM_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public Long getRoomId() {
		return roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.ROOM_ID
	 * @param roomId  the value for RMS2.ROOM.ROOM_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setRoomId(Long roomId) {
		this.roomId = roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.ROOM_NAME
	 * @return  the value of RMS2.ROOM.ROOM_NAME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public String getRoomName() {
		return roomName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.ROOM_NAME
	 * @param roomName  the value for RMS2.ROOM.ROOM_NAME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setRoomName(String roomName) {
		this.roomName = roomName == null ? null : roomName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.BUILDING_ID
	 * @return  the value of RMS2.ROOM.BUILDING_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public Long getBuildingId() {
		return buildingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.BUILDING_ID
	 * @param buildingId  the value for RMS2.ROOM.BUILDING_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setBuildingId(Long buildingId) {
		this.buildingId = buildingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.ROOM_NO
	 * @return  the value of RMS2.ROOM.ROOM_NO
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public String getRoomNo() {
		return roomNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.ROOM_NO
	 * @param roomNo  the value for RMS2.ROOM.ROOM_NO
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo == null ? null : roomNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.PRICE
	 * @return  the value of RMS2.ROOM.PRICE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.PRICE
	 * @param price  the value for RMS2.ROOM.PRICE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.CREATE_TIME
	 * @return  the value of RMS2.ROOM.CREATE_TIME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.CREATE_TIME
	 * @param createTime  the value for RMS2.ROOM.CREATE_TIME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.OPEN_DATE
	 * @return  the value of RMS2.ROOM.OPEN_DATE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public Date getOpenDate() {
		return openDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.OPEN_DATE
	 * @param openDate  the value for RMS2.ROOM.OPEN_DATE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RMS2.ROOM.IMAGE
	 * @return  the value of RMS2.ROOM.IMAGE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public byte[] getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RMS2.ROOM.IMAGE
	 * @param image  the value for RMS2.ROOM.IMAGE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public void setImage(byte[] image) {
		this.image = image;
	}
}