package demo.vo;

public class RoomConst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RMS2.ROOM
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String TABLE_ROOM = "ROOM";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.ROOM_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_ROOM_ID = "ROOM_ID";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.ROOM_NAME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_ROOM_NAME = "ROOM_NAME";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.BUILDING_ID
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_BUILDING_ID = "BUILDING_ID";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.ROOM_NO
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_ROOM_NO = "ROOM_NO";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.PRICE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_PRICE = "PRICE";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.CREATE_TIME
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_CREATE_TIME = "CREATE_TIME";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.OPEN_DATE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_OPEN_DATE = "OPEN_DATE";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RMS2.ROOM.IMAGE
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public static final String COLUMN_IMAGE = "IMAGE";

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RMS2.ROOM
	 * @mbggenerated  Thu May 09 15:40:46 CST 2013
	 */
	public RoomConst() {
		super();
	}
}